# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authenticator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='authenticator.proto',
  package='authenticator',
  syntax='proto3',
  serialized_pb=_b('\n\x13\x61uthenticator.proto\x12\rauthenticator\x1a\x1fgoogle/protobuf/timestamp.proto\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1c\n\rLoginResponse\x12\x0b\n\x03jwt\x18\x01 \x01(\t\"\x1d\n\x0eProfileRequest\x12\x0b\n\x03jwt\x18\x01 \x01(\t\"W\n\x0fProfileResponse\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x32\n\x0elast_logged_in\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\xa1\x01\n\rAuthenticator\x12\x44\n\x05Login\x12\x1b.authenticator.LoginRequest\x1a\x1c.authenticator.LoginResponse\"\x00\x12J\n\x07Profile\x12\x1d.authenticator.ProfileRequest\x1a\x1e.authenticator.ProfileResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LOGINREQUEST = _descriptor.Descriptor(
  name='LoginRequest',
  full_name='authenticator.LoginRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='authenticator.LoginRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='authenticator.LoginRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=121,
)


_LOGINRESPONSE = _descriptor.Descriptor(
  name='LoginResponse',
  full_name='authenticator.LoginResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='jwt', full_name='authenticator.LoginResponse.jwt', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=151,
)


_PROFILEREQUEST = _descriptor.Descriptor(
  name='ProfileRequest',
  full_name='authenticator.ProfileRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='jwt', full_name='authenticator.ProfileRequest.jwt', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=182,
)


_PROFILERESPONSE = _descriptor.Descriptor(
  name='ProfileResponse',
  full_name='authenticator.ProfileResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='authenticator.ProfileResponse.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_logged_in', full_name='authenticator.ProfileResponse.last_logged_in', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=271,
)

_PROFILERESPONSE.fields_by_name['last_logged_in'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['LoginRequest'] = _LOGINREQUEST
DESCRIPTOR.message_types_by_name['LoginResponse'] = _LOGINRESPONSE
DESCRIPTOR.message_types_by_name['ProfileRequest'] = _PROFILEREQUEST
DESCRIPTOR.message_types_by_name['ProfileResponse'] = _PROFILERESPONSE

LoginRequest = _reflection.GeneratedProtocolMessageType('LoginRequest', (_message.Message,), dict(
  DESCRIPTOR = _LOGINREQUEST,
  __module__ = 'authenticator_pb2'
  # @@protoc_insertion_point(class_scope:authenticator.LoginRequest)
  ))
_sym_db.RegisterMessage(LoginRequest)

LoginResponse = _reflection.GeneratedProtocolMessageType('LoginResponse', (_message.Message,), dict(
  DESCRIPTOR = _LOGINRESPONSE,
  __module__ = 'authenticator_pb2'
  # @@protoc_insertion_point(class_scope:authenticator.LoginResponse)
  ))
_sym_db.RegisterMessage(LoginResponse)

ProfileRequest = _reflection.GeneratedProtocolMessageType('ProfileRequest', (_message.Message,), dict(
  DESCRIPTOR = _PROFILEREQUEST,
  __module__ = 'authenticator_pb2'
  # @@protoc_insertion_point(class_scope:authenticator.ProfileRequest)
  ))
_sym_db.RegisterMessage(ProfileRequest)

ProfileResponse = _reflection.GeneratedProtocolMessageType('ProfileResponse', (_message.Message,), dict(
  DESCRIPTOR = _PROFILERESPONSE,
  __module__ = 'authenticator_pb2'
  # @@protoc_insertion_point(class_scope:authenticator.ProfileResponse)
  ))
_sym_db.RegisterMessage(ProfileResponse)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class AuthenticatorStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.Login = channel.unary_unary(
          '/authenticator.Authenticator/Login',
          request_serializer=LoginRequest.SerializeToString,
          response_deserializer=LoginResponse.FromString,
          )
      self.Profile = channel.unary_unary(
          '/authenticator.Authenticator/Profile',
          request_serializer=ProfileRequest.SerializeToString,
          response_deserializer=ProfileResponse.FromString,
          )


  class AuthenticatorServicer(object):

    def Login(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def Profile(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_AuthenticatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Login': grpc.unary_unary_rpc_method_handler(
            servicer.Login,
            request_deserializer=LoginRequest.FromString,
            response_serializer=LoginResponse.SerializeToString,
        ),
        'Profile': grpc.unary_unary_rpc_method_handler(
            servicer.Profile,
            request_deserializer=ProfileRequest.FromString,
            response_serializer=ProfileResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'authenticator.Authenticator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaAuthenticatorServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def Login(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def Profile(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaAuthenticatorStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def Login(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    Login.future = None
    def Profile(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    Profile.future = None


  def beta_create_Authenticator_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('authenticator.Authenticator', 'Login'): LoginRequest.FromString,
      ('authenticator.Authenticator', 'Profile'): ProfileRequest.FromString,
    }
    response_serializers = {
      ('authenticator.Authenticator', 'Login'): LoginResponse.SerializeToString,
      ('authenticator.Authenticator', 'Profile'): ProfileResponse.SerializeToString,
    }
    method_implementations = {
      ('authenticator.Authenticator', 'Login'): face_utilities.unary_unary_inline(servicer.Login),
      ('authenticator.Authenticator', 'Profile'): face_utilities.unary_unary_inline(servicer.Profile),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Authenticator_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('authenticator.Authenticator', 'Login'): LoginRequest.SerializeToString,
      ('authenticator.Authenticator', 'Profile'): ProfileRequest.SerializeToString,
    }
    response_deserializers = {
      ('authenticator.Authenticator', 'Login'): LoginResponse.FromString,
      ('authenticator.Authenticator', 'Profile'): ProfileResponse.FromString,
    }
    cardinalities = {
      'Login': cardinality.Cardinality.UNARY_UNARY,
      'Profile': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'authenticator.Authenticator', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
