# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities

import authenticator_pb2 as authenticator__pb2


class AuthenticatorStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Login = channel.unary_unary(
        '/authenticator.Authenticator/Login',
        request_serializer=authenticator__pb2.LoginRequest.SerializeToString,
        response_deserializer=authenticator__pb2.LoginResponse.FromString,
        )
    self.Profile = channel.unary_unary(
        '/authenticator.Authenticator/Profile',
        request_serializer=authenticator__pb2.ProfileRequest.SerializeToString,
        response_deserializer=authenticator__pb2.ProfileResponse.FromString,
        )


class AuthenticatorServicer(object):

  def Login(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Profile(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AuthenticatorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Login': grpc.unary_unary_rpc_method_handler(
          servicer.Login,
          request_deserializer=authenticator__pb2.LoginRequest.FromString,
          response_serializer=authenticator__pb2.LoginResponse.SerializeToString,
      ),
      'Profile': grpc.unary_unary_rpc_method_handler(
          servicer.Profile,
          request_deserializer=authenticator__pb2.ProfileRequest.FromString,
          response_serializer=authenticator__pb2.ProfileResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'authenticator.Authenticator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
